occupations_list = ["Accountant", "Acrobat", "Agency Detective", "Ambassador",
 "Antique Dealer", "Architect", "Artist", "Author",
 "Bank Robber", "Barber", "Bartender", "Bible Salesman",
 "Big Game Hunter", "Book Dealer", "Bookie", "Boss",
 "Bounty Hunter", "Boxer", "Burglar", "Bus Driver",
 "Catholic Priest", "Clergyman", "Clerk", "Cocktail Waitress",
 "Communist/Radical", "Company Officer/Executive", "Columnist", "Con Man",
 "Deacon/Elder", "Deep-Sea Diver", "Dentist", "Designer",
 "Dilettante", "DJ", "Drifter", "Editor",
 "Elected Official", "Entertainer", "Explorer", "Farmer",
 "Federal Agent", "Fence", "Field Researcher", "Film Crew",
 "Film Star", "Fireman", "Foreign Correspondent", "Forger/Counterfeiter",
 "Forester", "Forensic Investigator", "Forensic Surgeon", "Gambler",
 "Gangster", "Gardener", "Golf Pro", "Gravedigger",
 "Hacker", "Hired Goon", "Hit Man", "Hobo",
 "Hooker", "Journalist", "Judge", "Lawyer",
 "Librarian", "Loan Shark", "Lumberjack", "Manager/Coach",
 "Medical Technician", "Mental Hospital Attendant", "Mercenary", "Military Officer",
 "Miner", "Missionary", "Mountain Climber", "Museum Curator",
 "Musician", "News Chopper Pilot", "Nurse", "Occultist",
 "Painter/Sculptor", "Parapsychologist", "Pharmacist", "Photographer",
 "Photojournalist", "Physician", "Pick Pocket", "Pilot",
 "Plastic Surgeon", "Police Detective", "Policeman", "Practising Attorney",
 "Preacher", "Private Investigator", "Professional Athlete", "Professor/Teacher",
 "Programmer", "Prosecuting Attorney", "Protestant Minister", "Psychologist",
 "Punk", "Rabbi", "Racecar Driver", "Ranch Hand/Cowboy",
 "Reporter", "Researcher", "Sailor", "Salesman",
 "Secretary", "Shifty Accountant/Lawyer", "Small Business Owner", "Smuggler",
 "Soldier/Marine", "Spy", "Stage Actor", "Stage Hand",
 "Stock Broker", "Student/Intern", "Stunt Man", "Surveyor",
 "Swimmer/Diver", "Talent Agent", "Taxi Driver", "Telephone Operator",
 "Tennis Pro", "Tribal Member", "Undertaker", "Uniformed Police Officer",
 "Union Activist", "Writer", "Wrestler", "Zookeeper"]